name: gital_flutter
description: "A new Flutter project."

publish_to: "none"

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  rxdart: ^0.28.0
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  injectable: ^2.5.2
  slang: ^4.6.0
  slang_flutter: ^4.6.0
  flutter_svg: ^2.0.17
  flutter_secure_storage: ^9.2.4
  dio: ^5.8.0+1
  retrofit: ^4.7.3
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  permission_handler: ^12.0.1
  url_launcher: ^6.3.1
  auto_route: ^10.2.0
  amplitude_flutter: ^4.3.0
  flutter_localizations:
    sdk: flutter
  dynamic_fonts: ^2.2.1
  intl: ^0.20.2
  envied: ^1.1.1
  flutter_native_splash: ^2.4.5
  firebase_core: ^3.13.0
  sheet: ^1.0.0
  nonce: ^1.2.0
  crypto: ^3.0.6
  flutter_web_auth_2: ^4.1.0
  adaptive_dialog: ^2.4.1
  collection: ^1.19.1
  device_info_plus: ^11.5.0
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  mutex: ^3.1.0
  uuid: ^4.5.1
  web_socket_channel: ^3.0.3
  bloc_concurrency: ^0.3.0
  firebase_messaging: ^15.2.10
  app_links: ^6.4.1
  intersperse: ^2.0.0
  share_plus: ^12.0.0
  firebase_crashlytics: ^4.3.10
  firebase_analytics: ^11.6.0
  package_info_plus: ^9.0.0
  pub_semver: ^2.2.0
  flutter_exit_app: ^2.0.0
  logging: ^1.3.0
  characters: ^1.3.0
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.10.0
  retrofit_generator: ^10.0.6
  json_serializable: ^6.9.4
  freezed: ^3.0.4
  auto_route_generator: ^10.2.5
  flutter_launcher_icons: ^0.14.3
  hive_ce_generator: ^1.10.0
  injectable_generator: ^2.9.0
  envied_generator: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/fonts/

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true
